<?xml version="1.0" encoding="utf-8"?><Database Name="Enseignement" Class="DataClassesEnseignementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=pavillon\sqlexpress;Initial Catalog=Enseignement;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EnseignementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Eleves" Member="Eleves">
    <Type Name="Eleves">
      <Column Name="Id_eleve" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cne" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenom" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="tel" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>